comment out the DMA directory
This directory is required to compile but does not exist in the source tree.

Compile failed at ../../cherilibs/trunk/MemTypes.bsv:

root@ruisrv:~/lab/sva/cheri/beri/beri/cheri/trunk# bash setup.sh
Bluespec paths successfully configured for version 2019.05.beta2-debian9stretch-amd64
Quartus paths successfully configured for version 13v1
root@ruisrv:~/lab/sva/cheri/beri/beri/cheri/trunk# make sim COP1=1
make -C ../../cherilibs/trunk/peripherals pism
make[1]: Entering directory '/root/lab/sva/cheri/beri/beri/cherilibs/trunk/peripherals'
bison -dy pismdev/config.y
pismdev/config.y:183.9-13: warning: type clash on default action: <pd> != <> [-Wother]
 	param
         ^^^^^
mv -f y.tab.c config.c
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o config.o config.c
pismdev/config.y: In function 'device_finish':
pismdev/config.y:291:7: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
  bool ret;
       ^
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o pism.o pismdev/pism.c
lex  -t pismdev/scan.l > scan.c
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o scan.o scan.c
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o pism_device.o pismdev/pism_device.c
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed -shared -o libpism.so pism.o config.o scan.o pism_device.o
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o dram.o pismdev/dram/dram.c
cc -fPIC -g -Wall -L . -shared -o dram.so dram.o libpism.so -lpism
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o ethercap.o pismdev/ether/ethercap.c
cc -fPIC -g -Wall -L . -shared -o ethercap.so ethercap.o libpism.so -lpism
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o fb.o pismdev/framebuffer/fb.c
cc -fPIC -g -Wall -L . -shared -o fb.so fb.o libpism.so -lSDL -lpism
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o sdcard.o pismdev/sdcard/sdcard.c
cc -fPIC -g -Wall -L . -shared -o sdcard.so sdcard.o libpism.so -lpism
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o virtio_block.o pismdev/virtio/virtio_block.c
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o virtio.o pismdev/virtio/virtio.c
cc -fPIC -g -Wall -L . -shared -o virtio_block.so virtio_block.o virtio.o libpism.so -lbsd -lpism
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o uart.o pismdev/uart/uart.c
cc -fPIC -g -Wall -L . -shared -o uart.so uart.o libpism.so -lpism
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed   -c -o chericonf.o pismdev/chericonf.c
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed -ldl -o chericonf chericonf.o config.o scan.o pism_device.o pism.o
cc -fPIC -g -Wall -I.. -I. -Wl,--no-as-needed -o pismtest pismdev/pismtest.c -ldl -L . -lpism
rm scan.c config.c
make[1]: Leaving directory '/root/lab/sva/cheri/beri/beri/cherilibs/trunk/peripherals'
rm -f ../../cherilibs/trunk/MEM.bo
mkdir -p ./build_fpu_sim
CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 MAKEFLAGS= bsc -p +:%/Libraries/TLM3:%/Libraries/Axi:%/Libraries/Contrib/NonPipelinedMath:../../cherilibs/trunk/peripherals/LoopbackUART:../../cherilibs/trunk/peripherals/DMA:../../cherilibs/trunk/peripherals/PixelStream:../../cherilibs/trunk/peripherals/Compositor:FPU:FPU/megafunctions:../../cherilibs/trunk:../../cherilibs/trunk/debugging:../../cherilibs/trunk/AsymmetricBRAM:Test/Mem:../../cherilibs/trunk/BlueCheck +RTS -K4000M -RTS -check-assert -no-warn-action-shadowing -show-schedule -parallel-sim-link 4 -D MEM256 -Xl -Wl,-rpath=../../cherilibs/trunk/peripherals -L ../../cherilibs/trunk/peripherals -l pism -parallel-sim-link 4  -l mpfr -l gmp -simdir ./build_fpu_sim -bdir ./build_fpu_sim -u -sim -D STATCOUNTERS -D UNALIGNEDMEMORY -D COP1 -D BLUESIM -D DEBUG_INST-show-schedule ../../cherilibs/trunk/TopSimAxi.bsv
Warning: Command line: (S0091)
  Removing a directory from the path specified with the -p flag, because it
  could not be opened.
  Directory:
    ../../cherilibs/trunk/peripherals/DMA
  System message:
    does not exist
checking package dependencies
compiling ../../cherilibs/trunk/PISM.bsv
Foreign import file created: ./build_fpu_sim/c_getchar.ba
Foreign import file created: ./build_fpu_sim/pism_init.ba
Foreign import file created: ./build_fpu_sim/pism_cycle_tick.ba
Foreign import file created: ./build_fpu_sim/pism_interrupt_get.ba
Foreign import file created: ./build_fpu_sim/pism_request_ready.ba
Foreign import file created: ./build_fpu_sim/pism_request_put.ba
Foreign import file created: ./build_fpu_sim/pism_response_ready.ba
Foreign import file created: ./build_fpu_sim/pism_response_get.ba
Foreign import file created: ./build_fpu_sim/pism_addr_valid.ba
Foreign import file created: ./build_fpu_sim/debug_stream_init.ba
Foreign import file created: ./build_fpu_sim/debug_stream_sink_ready.ba
Foreign import file created: ./build_fpu_sim/debug_stream_sink_put.ba
Foreign import file created: ./build_fpu_sim/debug_stream_source_ready.ba
Foreign import file created: ./build_fpu_sim/debug_stream_source_get.ba
compiling ../../cherilibs/trunk/Debug.bsv
compiling ../../cherilibs/trunk/AvalonStreaming.bsv
compiling ../../cherilibs/trunk/AxiBridge.bsv
compiling ../../cherilibs/trunk/MasterSlave.bsv
compiling ../../cherilibs/trunk/Interconnect.bsv
Warning: "../../cherilibs/trunk/Interconnect.bsv", line 602, column 5: (P0221)
  Partial type information for this function is being ignored. At the moment,
  only full type declarations are supported. If a type is missing for the
  return value or any of the arguments, then all types are ignored.
Warning: "../../cherilibs/trunk/Interconnect.bsv", line 656, column 5: (P0221)
  Partial type information for this function is being ignored. At the moment,
  only full type declarations are supported. If a type is missing for the
  return value or any of the arguments, then all types are ignored.
compiling ../../cherilibs/trunk/MemTypes.bsv
Error: "../../cherilibs/trunk/MemTypes.bsv", line 411, column 20: (T0142)
  Pattern for constructor `Write' of type
  MemTypes::MemoryResponse_$operation#(a__, b__, c__) requires 0 arguments,
  found 1.
Makefile:514: recipe for target 'build_fpu_sim/sim' failed
make: *** [build_fpu_sim/sim] Error 1
root@ruisrv:~/lab/sva/cheri/beri/beri/cheri/trunk#